server:
  port: 9000

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb+srv://xch52:zfJV0eAOAf8eg3nk@cluster0.nqdvk3f.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: mydatabase

